### ISSUE TITLE
support [toc]

### ISSUE THREAD

**Issue by zhenfeng-zhu** [denoland/deno_blog#105]
I find the `[toc]` tag is not supproted.

<img width="191" alt="image" src="https://user-images.githubusercontent.com/6822558/211963630-37e38a97-c810-49a4-8e85-1c27ae94facf.png">

**Comment by zhenfeng-zhu** [comment]
> 

sorry,  it's not the blog tag. 

The `[toc]` is a markdown syntax, means table of content. it will show the article outline.

**Comment by Felipe-53** [comment]
I see...

As far as I can see this `[toc]` tag in not part of the [Github Flavoured Markdown Specification](https://github.github.com/gfm/), so I don't know if this is going to be implemented, though I do think it is a nice feature.

But then again this a minimalisc solution to blogging. I guess if you really want this you can fork the project and add it, I think there aew libs for that.
