### ISSUE TITLE
toggle html sanitization

### ISSUE THREAD

**Issue by capogreco** [denoland/deno_blog#108]
It would be nifty to be able to javascript Canvas API things from within markdown, imo.

many thanks,

**Comment by KorigamiK** [comment]
Agreed. I can vouch for this feature. Maybe a `sanitize_html` parameter in the frontmatter would be helpful.

**Comment by lino-levan** [comment]
This is an upstream issue. Looking into creating a PR upstream and then making a PR here to add this feature.

Would `sanitize_html` make most sense as a global option for the blog or in the front matter?

**Comment by capogreco** [comment]
In the front matter, I would say. This would be in keeping with Deno's idiom of explicit tags etc.

**Comment by lino-levan** [comment]
ref: https://github.com/denoland/deno-gfm/pull/34

**Comment by capogreco** [comment]
any movement on this front?

**Comment by lino-levan** [comment]
Waiting on @crowlKats to review my PR upstream. Just pinged him again. Technically twice since this message is also pinging him (sorry!)

**Comment by lino-levan** [comment]
Cool, looks like upstream got merged. Will make a PR tomorrow here to add this as an option. Thanks for your patience!

**Comment by lino-levan** [comment]
I believe this is currently blocked on https://github.com/denoland/deno-gfm not having a new tag including this change. Waiting on that before I open a PR.

**Comment by crowlKats** [comment]
@lino-levan it does have a tag for this.

**Comment by lino-levan** [comment]
Ah you're right, I had looked at the releases instead of the tags. I should have known better since I knew that gfm was at version 0.1.28. Will open a PR right now, assuming my food doesn't get here first.

**Comment by capogreco** [comment]
Is there anything else we need to do other than put `disable_html_sanitization: true` in the front matter of the markdown file?

I am having trouble getting this working.

**Comment by lino-levan** [comment]
Please see my comment in #119
