### ISSUE TITLE
How can you change the text color?

### ISSUE THREAD

**Issue by SwiftyProgrammer690** [denoland/deno_blog#115]
Hi, is there a way I can change my text's theme to light mode? Is there a method in the `blog();` method like there is for `title`, `description`, `author`, etc. like in down below?

```
blog({
  title: "Egyptian Religion....",
  description: "and why it was important to the people...",
  author: "Deno"
)};
```

**Comment by KorigamiK** [comment]
You can add your custom stylesheet in the blog constructor

```
Blog({
    ...
    style: "h1 {color: white;}",
})
```

**Comment by SwiftyProgrammer690** [comment]
> You can add your custom stylesheet in the blog constructor
> 
> ```
> blog({
>     ...
>     style: "h1 {color: white;}",
> })
> ```

Yeah, but like what if I wanted to change the whole ***theme*** itself? Is there a CSS or JSON method fo that?

**Comment by KorigamiK** [comment]
The blog is configured using UnoCSS so you may configure the styles according to you. 

```
unocss?: UnoConfig;
```

**Comment by SwiftyProgrammer690** [comment]
Thank you for your help @KorigamiK
