### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by jimizai** [denoland/deno_blog#2]
Request /hmr.js, return "Internal server error"
Function fromFileUrl throwed error: Uncaught TypeError: Must be a file URL

**Comment by bartlomieju** [comment]
How are you running it?

**Comment by jimizai** [comment]
I used cli tool. 
```shell
$ deno run https://deno.land/x/blog/init.ts ./directory/for/blog/
$ deno run -A main.ts --dev
```

**Comment by jimizai** [comment]
Is there a way to solve the problem of online and local file paths?

**Comment by bartlomieju** [comment]
@jimizai what do you mean? HMR should work in both cases now

**Comment by jimizai** [comment]
@bartlomieju no problem thanks
