### ISSUE TITLE
Incorrect date displayed on posts in dev environment

### ISSUE THREAD

**Issue by tristanisham** [denoland/deno_blog#47]
When working on new posts, edition your sites files, or doing any task while `deno task dev` is running, the date displayed on posts is a day behind. 

```md
---
title: Hello world!
publish_date: 2022-07-13
---
```
Results in 07/12/22 being displayed in the development environment. In production on Deno Deploy this is a non-issue but I keep having this bug on a variety of Linux distros.

**Production**
![image](https://user-images.githubusercontent.com/23124818/178838244-4d6e82fd-8e44-4902-8b6b-33f35b8d3bec.png)

**Comment by geoffreypetri** [comment]
Hello @tristanisham,
Is it possible to get some more details about your setup ?
I just tried and don't notice the behavior you describe (with deno_blog 0.4.1 and 0.4.2).

**Comment by tristanisham** [comment]
Hi @geoffreypetri, I'm currently using Deno Blog on WSL Debian 11/OpenSUSE Tumbleweed on 0.4.2. I'm also using the latest version of Deno.

**Comment by geoffreypetri** [comment]
OK, I can't reproduce your issue.
The [current implementation](https://github.com/denoland/deno_blog/blob/a7d19f4653cea5f4ef2c232345d04efc3acfea9c/components.tsx#L291) uses `Date.toLocaleDateString` so my guess is your setup sets a wrong timezone ?
```ts
  const formatted = date.toLocaleDateString(lang ?? "en-US", { dateStyle });
```

**Comment by tristanisham** [comment]
Let me attempt and report back.
