### ISSUE TITLE
Is there a will to use Fresh under the hood ?

### ISSUE THREAD

**Issue by geoffreypetri** [denoland/deno_blog#50]

**Comment by bartlomieju** [comment]
Fresh is already used in other "showcase" apps that we presented in recent months, I think it makes more sense that blog (which is the simplest of the apps) to use some other technology.

**Comment by geoffreypetri** [comment]
Hello,
Thanks for your reply and understood.
I just saw the branch `use_oak` and thought it would make more sense in the Deno ecosystem that `blog` uses the Fresh framework.
