### ISSUE TITLE
Add "x min read" prompt

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_blog#59]
Example implementation: https://w3collective.com/calculate-reading-time-javascript/

This should be possible to disable it but enabled by default.

**Comment by vixalien** [comment]
Should calculate read time based on original markdown source? or compile it to html, then use a virtual dom library to get actual text from compiled html?

**Comment by bartlomieju** [comment]
Original markdown source makes more sense to be and wouldn't require any client side code.

**Comment by vixalien** [comment]
I meant a virtual dom library on deno. also using the original markdown source means it's not gonna be 100% accurate (which is fine) since it will be unaware of stuff like repeated links (inside []) and other stuff.

**Comment by bartlomieju** [comment]
That's fine enough, it will always be just an approximation.

**Comment by vixalien** [comment]
okay.

**Comment by felix-schindler** [comment]
This attempt doesn't work on something like Chinese or Japanese.

**Comment by rottenpen** [comment]
> This attempt doesn't work for languages like Chinese or Japanese.

or author can override it？

**Comment by lino-levan** [comment]
#74 got merged a while ago, has this not been resolved?
