### ISSUE TITLE
All errors are “Internal server error”，I find it hard to debug

### ISSUE THREAD

**Issue by rottenpen** [denoland/deno_blog#62]
Is it better to return it directly?

<img width="851" alt="image" src="https://user-images.githubusercontent.com/12029924/183295201-01f3926b-d169-4dc0-b75a-4891253d2f54.png">

**Comment by ije** [comment]
agreed, PR welcome anyway

**Comment by rottenpen** [comment]
@ije #64

**Comment by ije** [comment]
thanks!
