### ISSUE TITLE
TypeError on Deno Deploy

### ISSUE THREAD

**Issue by pazguille** [denoland/deno_blog#77]
Hi, I have this error after create a new version of my [blog](https://github.com/pazguille/blog).

```
TypeError: Cannot read properties of undefined (reading 'rid')
    at https://deno.land/std@0.154.0/node/_process/streams.mjs:137:35
```

<img width="1030" alt="blog_pazguille_me_-_Project_-_Deploy" src="https://user-images.githubusercontent.com/250856/188439626-b963ce40-0961-4bb0-af1b-9d66f7885771.png">

**Comment by musab** [comment]
+1 also to note, this only happens during deploy. Running locally via ‘deno task …’ works without errors.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kt3k** [comment]
We downgraded std version in esm.sh to v0.153.0. Now re-deploying should fix the above issue.

**Comment by pazguille** [comment]
Yes, it's working.
