### ISSUE TITLE
Slow Loads

### ISSUE THREAD

**Issue by willpuckett** [denoland/deno_blog#87]
Blog is hosted on deno deploy at https://smote.io and is taking about 7 seconds to load on initial load. Once it's been loaded, it moves normally. There's no warnings or errors coming out of the logs... Is this normal?

**Comment by lino-levan** [comment]
Definitely not normal, what are you hosting this on?

**Comment by lino-levan** [comment]
Ah, I am blind you said deploy. Just a few comments:
- Are you using a caching layer of any kind (Cloudflare, etc)?
- Can you reproduce this slowdown locally?
- Is the blog open-source? Can I take a look?

**Comment by willpuckett** [comment]
Yes blog is on Deno Deploy at https://smote.io. The repo is available at https://github.dev/willpuckett/smote.

I modified the deno_blog source code to produce some timing information by chaining the `loadContent()` function in `blog.tsx` to the following: 

```ts
async function loadContent(blogDirectory: string, isDev: boolean) {
  // Read posts from the current directory and store them in memory.
  const postsDirectory = join(blogDirectory, "posts");

  let post_load_time = 0;
  // TODO(@satyarohith): not efficient for large number of posts.
  for await (
    const entry of walk(postsDirectory)
  ) {
    const t0 = performance.now();
    if (entry.isFile && entry.path.endsWith(".md")) {
      await loadPost(postsDirectory, entry.path);
    }
    const t1 = performance.now();
    const entry_performance = t1 - t0;
    console.log(`Load ${entry.name} took ${entry_performance} milliseconds.`);
    post_load_time += entry_performance;

  }

  console.log(`Total post load time: ${post_load_time}`);

  
  if (isDev) {
    watchForChanges(postsDirectory).catch(() => {});
  }
}
```

It runs very quickly on my local machine, but the timing on Deno Deploy takes much longer. Here's a sample:

<img width="1134" alt="Screenshot 2023-01-31 at 1 11 38 PM" src="https://user-images.githubusercontent.com/12959477/215887104-037131ba-488b-4fcb-94a6-ef640fb97a6c.png">

No caching (that I'm aware of)....

**Comment by lino-levan** [comment]
Last week I was able to reproduce the slowdowns but I can't anymore. Can you still reproduce this?

**Comment by willpuckett** [comment]
Yes it’s definitely still happening.

From the beginning, it seems to only happen when an isolate is spinning up. Then, it’s normal/snappy for a while, and then when what I imagine is an isolate becomes inactive, the long start up time recurs.

I don’t know if it’s a network latency issue or if it’s simply slow parsing the markdown.




On Jan 31, 2023, at 2:41 PM, Lino Le Van ***@***.***> wrote:


Last week I was able to reproduce the slowdowns but I can't anymore. Can you still reproduce this?

**Comment by willpuckett** [comment]
Just updated to the latest pushes in the [repo](https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx) and it’s taking 7 seconds from isolate spin up to serve.


￼
On Feb 3, 2023, at 2:32 PM, gmail ***@***.***> wrote:

Yes it’s definitely still happening.

From the beginning, it seems to only happen when an isolate is spinning up. Then, it’s normal/snappy for a while, and then when what I imagine is an isolate becomes inactive, the long start up time recurs.

I don’t know if it’s a network latency issue or if it’s simply slow parsing the markdown.




On Jan 31, 2023, at 2:41 PM, Lino Le Van ***@***.***> wrote:


Last week I was able to reproduce the slowdowns but I can't anymore. Can you still reproduce this?

**Comment by ayame113** [comment]
`loadPost` is currently running serially.
https://github.com/denoland/deno_blog/blob/0a43328bc1d890ed21ea8938bac049d78001250a/blog.tsx#L194-L203

How about changing this to run in parallel? (As follows)

```ts
const loadingPromises: Promise<void>[] = [];

for await (const entry of walk(postsDirectory)) {
  if (entry.isFile && entry.path.endsWith(".md")) {
    loadingPromises.push(loadPost(postsDirectory, entry.path));
  }
}

await Promise.all(loadingPromises);
```

**Comment by willpuckett** [comment]
World of genius. Load time goes from about 9 seconds to under two. This should be the accepted answer.

On Feb 4, 2023, at 11:39 AM, ayame113 ***@***.***> wrote:


loadPost is currently running serially.
https://github.com/denoland/deno_blog/blob/0a43328bc1d890ed21ea8938bac049d78001250a/blog.tsx#L194-L203

How about changing this to run in parallel? (As follows)

const loadingPromises: Promise<void>[] = [];

for await (const entry of walk(postsDirectory)) {
  if (entry.isFile && entry.path.endsWith(".md")) {
    loadingPromises.push(loadPost(postsDirectory, entry.path));
  }
}

await Promise.all(loadingPromises);
