### ISSUE TITLE
BUG: Non-unicode markdown files not support.

### ISSUE THREAD

**Issue by gmqiyue** [denoland/deno_blog#91]
> Sorry, my english is very poor!

##

Non-unicode markdown files not support.

## Steps

1. Create markdown file into `posts` folder, filename use "中文名称.md".
2. Start deno server `deno task dev`.
3. Click 'Read More' on website.
4. Result is 'Not Found'

<img width="914" alt="image" src="https://user-images.githubusercontent.com/87467755/195271300-4ef6384f-3312-40fc-82b6-f87f0b762f58.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/87467755/195271443-51a95d0f-99af-470c-aaf6-9a0966b0e2c2.png">

**Comment by zhenfeng-zhu** [comment]
@gmqiyue Hi, meet this bug too, and then I create a pr to fix it.
