### ISSUE TITLE
The order of middleware is changed round and round every time.

### ISSUE THREAD

**Issue by s-uei** [denoland/deno_blog#92]
Hi.

I found a bug in `composeMiddlewares`.

https://github.com/denoland/deno_blog/blob/36cc6c3c578a1e42247bad6b5aa2b36dce6b6643/blog.tsx#L138

The `reverse` function change the array of caller by breaking. The order of `state.middlrewares` change every time.

I recommend using `slice().reverse()` instead of `reverse()`.

**Comment by lino-levan** [comment]
#93 got merged, shouldn't this issue be closed?
